site_name: AnimalPoseTracker
site_url: https://animalposetracker.github.io/
site_author: Adam Wiveion
site_description: A guide to use AnimalPoseTracker, a tool for cross-species animal pose estimation.
repo_url: https://github.com/AnimalPoseTracker/docs/animalposetracker/
